### ISSUE TITLE
i cant e gaps when i pvp

### ISSUE THREAD

**Issue by master7720** [momentumdevelopment/cosmos#105]
Issue:
* What is the bug that you would like addressed?

Context:
* When does this bug happen? Does it persist after restart/toggle?

Environment: 
* What other clients do you run, PC setup, relevant servers? How can this bug be replicated?

Config:
* Attach any relevant parts of your config here.

**Comment by Sxmurai** [comment]
if youre on a strict server, this isnt really a cosmos issue. you cant gap while placing crystals for an example - or atleast theres no public bypass that im aware of yet for it.

**Comment by master7720** [comment]
no its on cc

**Comment by linustouchtips** [comment]
Please follow the template for reporting a bug, I can't really help you if all the information I have is "I cant e gaps when i pvp"
