### ISSUE TITLE
cev breaker and piston aura

### ISSUE THREAD

**Issue by master7720** [momentumdevelopment/cosmos#108]
Issue:
stuff
Context:
pvp

Environment: 
idk

Config:
no.

**Comment by Sxmurai** [comment]
Can you please follow the format for suggestions? There is legit a whole prompt for you to pick a preset to provide us with information cleanly about your suggestions. They're not there for fun or to look pretty.

On another note, please make this into separate issues.

**Comment by master7720** [comment]
title.

**Comment by Sxmurai** [comment]
Did you not read what I put last time on your last issue?
