### ISSUE TITLE
[IMPROVEMENT] Change NoSlow Ice

### ISSUE THREAD

**Issue by HausemasterIssue** [momentumdevelopment/cosmos#113]
Issue:
* What is the bug that you would like addressed?
The current option for ice in the NoSlow isn't very good. That just makes you go way faster on ice, which rubberbands you on a lot of servers and just isn't very good. However, if you change it similar to RusherHack's, where you simply don't slip at all and can just walk on it like normal terrain, that would be much better and fit the theme of the module.

Context:
* When does this bug happen? Does it persist after restart/toggle?
When you go on ice.

Environment: 
* What other clients do you run, PC setup, relevant servers? How can this bug be replicated?
Go on ice.

Config:
* Attach any relevant parts of your config here.
None.

**Comment by CynicalMuffin** [comment]
Or you could just make a separate module called ice speed and make a no slow like the one you said

**Comment by master7720** [comment]
> Or you could just make a separate module called ice speed and make a no slow like the one you said

rip perrys old account

**Comment by linustouchtips** [comment]
Fixed
