### ISSUE TITLE
[FEATURE] Cev Breaker

### ISSUE THREAD

**Issue by CynicalMuffin** [momentumdevelopment/cosmos#114]
basically cevbreaker but with options to support crystalpvp.cc where it is patched like having a option where after cev breaking once it swaps to a sword hits the player and then cev breaks again

This bypasses on cc as with a lot of configuration ive seen someone do it on gamesense

**Comment by linustouchtips** [comment]
I dont ever plan on making this module sorry

**Comment by CynicalMuffin** [comment]
no problem it was a suggestion after all
