### ISSUE TITLE
[SUGGESTION] for crystal aura

### ISSUE THREAD

**Issue by master7720** [momentumdevelopment/cosmos#117]
Issue:
face place heath

Context:
why i want this bc its useful for cpvping

Environment: 
N/A

Config:
N/A

**Comment by CynicalMuffin** [comment]
Fast place is already a feature

**Comment by CynicalMuffin** [comment]
Its in the override setting in CA

**Comment by linustouchtips** [comment]
Feature exists, it's called "Health" under the "Override" parent setting

**Comment by master7720** [comment]
oh lol ok my bad
