### ISSUE TITLE
[FEATURE] Toggle f3

### ISSUE THREAD

**Issue by CynicalMuffin** [momentumdevelopment/cosmos#121]
Toggle Third person perspective 

Basically switches to third person perspective when binded key held down and switches back to first person when not held down

**Comment by master7720** [comment]
hes talking about this https://www.youtube.com/watch?v=tASf5Bf8wuQ

**Comment by master7720** [comment]
https://www.curseforge.com/minecraft/mc-mods/perspective-mod-redux/download/2494279
