### ISSUE TITLE
[SUGGESTION] Enable Scrolling in the Clickgui

### ISSUE THREAD

**Issue by GerroPogi** [momentumdevelopment/cosmos#122]
Issue:
* What is the feature you would like added?

Context:
* This is because, when we are setting our config, we can't go below, and it would help if we could also customize the windows of the GUI.

**Comment by linustouchtips** [comment]
Scrolling already exists ...

**Comment by linustouchtips** [comment]
Send a video, I've tested it multiple times and I've never had an issue with scrolling in the ClickGUI. I've also never heard anyone else have an issue.
