### ISSUE TITLE
[SUGGESTION] HealthBar

### ISSUE THREAD

**Issue by NeCronuz** [momentumdevelopment/cosmos#123]
I think that healthbar will be a great innovation, since it is convenient to watch a player's HP using it 

Config:
location:vertically, horizontally 
Alive ticks

**Comment by linustouchtips** [comment]
like in the HUD? Or like nametags?

**Comment by CynicalMuffin** [comment]
im pretty sure he means ESP health bar like in 1.8 clients for vertically

**Comment by NeCronuz** [comment]
![HealthBar](https://user-images.githubusercontent.com/90137534/143866959-b1fd31b2-5efa-4413-9a78-a6c04221ed52.png)

**Comment by linustouchtips** [comment]
Closed in 89a5ad1
