### ISSUE TITLE
[SUGGESTION] Quiver

### ISSUE THREAD

**Issue by master7720** [momentumdevelopment/cosmos#124]
Quiver

Context:
* Why would this feature be useful? Have you tried any existing alternatives?bc its good for bow pvp on cc and sometimes on 2bpvp

Environment: 
* What other clients do you run, PC setup, relevant servers?

Config:
* Attach any relevant parts of your config here.

**Comment by CynicalMuffin** [comment]
Duplicate  #43

**Comment by master7720** [comment]
> Duplicate #43

oh rip didnt see that
