### ISSUE TITLE
[BUG] Surround doesn't work on ender chests

### ISSUE THREAD

**Issue by fxbT-zzz** [momentumdevelopment/cosmos#125]
Issue:
* What is the bug that you would like addressed?
Surround does not work on ender chests.

Context:
* When does this bug happen? Does it persist after restart/toggle?
When toggling surround while on an ender chest, it immediately turns surround off and doesn't place any blocks.

Environment: 
* What other clients do you run, PC setup, relevant servers? How can this bug be replicated?
Happens with only cosmos in the mods folder. Happens on all servers as well as singleplayer. Replicate it by toggling surround while on an ender chest.

Config:
* Attach any relevant parts of your config here.
Happens with default config and other configs too.

**Comment by master7720** [comment]
the surround doesnt work on strict unless my config is bad

**Comment by linustouchtips** [comment]
all of cosmos's modules work on strict, I've tested all of them. you likely configured it incorrectly.

**Comment by master7720** [comment]
i use the default config and it gives me ghost blocks on 2bpvp

**Comment by linustouchtips** [comment]
that's cause you're not supposed to used default config rofl

**Comment by master7720** [comment]
> that's cause you're not supposed to used default config rofl

bruh send me your surround config

**Comment by linustouchtips** [comment]
[ClickGUI]
Enabled = false
Drawn = false
Bind = 54
Mode = "WINDOW"
PrimaryColor = -7688248
BackgroundColor = -15263971
AccentColor = -14474451
SecondaryColor = -15987695
ComplexionColor = -15592936
PauseGame = false
WindowBlur = false
Blur = false

[Colors]
Enabled = true
Drawn = false
Bind = 0
Color = -57316616
Rainbow = "GRADIENT"
Rainbow-Speed = 50.5
Rainbow-Saturation = 0.35
Rainbow-Brightness = 1.0
Rainbow-Difference = 40.3

[DiscordPresence]
Enabled = true
Drawn = false
Bind = 0

[Font]
Enabled = false
Drawn = false
Bind = 0
Vanilla = true

[Social]
Enabled = false
Drawn = false
Bind = 0
Friends = true

[HUD]
Enabled = true
Drawn = false
Bind = 0
Watermark = true
ActiveModules = true
Coordinates = true
Speed = true
Ping = true
FPS = true
TPS = true
Armor = true
PotionEffects = false

[Aura]
Enabled = false
Drawn = true
Bind = 49
Iterations = 1.0
Variation = 100.0
Range = 6.0
WallsRange = 6.0
Timing = "SEQUENTIAL"
Timing-Mode = "SWING"
Timing-Factor = 1.0
Timing-Delay = 1000.0
Timing-Ticks = 15.0
Timing-TPS = "AVERAGE"
Timing-Switch = 0.0
Timing-Random = 0.0
Timing-TicksExisted = 0.0
Timer = 1.0
FOV = 180.0
Weapon = "SWORD"
Weapon-OnlyWeapon = true
Weapon-32K = false
Weapon-Block = false
Rotation = "PACKET"
Rotation-Limit = "NONE"
Bone = "EYES"
Rotation-Random = 0.0
Swing = "MAINHAND"
Raytrace = false
Packet = false
Teleport = false
Reactive = false
Merge = false
StopSprint = true
StopSneak = true
Pause = true
Pause-Health = 0.0
Pause-Eating = false
Pause-Mining = true
Pause-Mending = false
Switch = "NORMAL"
Target = "CLOSEST"
Target-Players = true
Target-Passives = false
Target-Neutrals = false
Target-Hostiles = false
Render = true

[AutoCrystal]
Enabled = true
Drawn = true
Bind = 19
Explode = true
Explode-Range = 5.0
Explode-WallRange = 3.5
Explode-Delay = 60.0
Explode-RandomDelay = 0.0
Explode-SwitchDelay = 0.0
Explode-TicksExisted = 1.0
Explode-Damage = 0.0
Explode-LocalDamage = 5.0
Explode-Limit = 10.0
Explode-Packet = true
Explode-Inhibit = true
Explode-Hand = "SYNC"
Explode-Weakness = "NONE"
Place = true
Place-Range = 5.0
Place-WallRange = 3.5
Place-Delay = 20.0
Place-Damage = 5.0
Place-LocalDamage = 5.0
Place-Packet = true
Place-Interact = "STRICT"
Place-Raytrace = "DOUBLE"
Place-Hand = "SYNC"
Place-Switch = "NONE"
Pause = true
Pause-Health = 2.0
Pause-Safety = true
Pause-Eating = false
Pause-Mining = false
Pause-Mending = false
Override = true
Override-Health = 10.0
Override-Threshold = 0.0
Override-Armor = 0.0
Rotation = "PACKET"
Rotation-Limit = "NONE"
Rotation-When = "BOTH"
Rotation-Random = 0.0
Calculations = true
Calculations-Timing = "SEQUENTIAL"
Calculations-TPS = "NONE"
Calculations-Placements = "NATIVE"
Calculations-Logic = "DAMAGE"
Calculations-Sync = "SOUND"
Calculations-Prediction = false
Calculations-IgnoreTerrain = false
Target = "CLOSEST"
Target-Range = 10.0
Target-Players = true
Target-Passives = false
Target-Neutrals = false
Target-Hostiles = false
Render = true
Render-Mode = "BOTH"
Render-Text = "NONE"
Render-Width = 1.6

[Burrow]
Enabled = false
Drawn = true
Bind = 48
Mode = "OBSIDIAN"
Rotation = "PACKET"
Offset = 2.2

[Criticals]
Enabled = false
Drawn = true
Bind = 49
Mode = "STRICT"
Motion = 0.4
Modifier = 1.5
Delay = 200.0
Delay-32K = 0.0
Teleport = false
Particles = true
Pause = true
Pause-Liquid = true
Pause-Air = true
Pause-Crystal = true
Pause-32K = true

[FastProjectile]
Enabled = false
Drawn = true
Bind = 0
Bows = false
Eggs = false
Snowballs = false
Ticks = 10.0

[HoleFill]
Enabled = false
Drawn = true
Bind = 34
Mode = "TARGETED"
Block = "OBSIDIAN"
Completion = "COMPLETION"
Range = 5.0
Threshold = 3.0
Switch = "NORMAL"
Strict = true
Safety = false
Doubles = true
Rotation = "PACKET"
Target = "CLOSEST"
Target-Range = 10.0
Render = true
Render-Mode = "FILL"

[Offhand]
Enabled = true
Drawn = false
Bind = 0
Item = "TOTEM"
FallBack = "CRYSTAL"
Interact = "STRICT"
Gapple = "SWORD"
Health = 16.0
Delay = 0.0
ArmorSafe = true
MotionStrict = false
Recursive = false
Pause = true
Pause-Liquid = false
Pause-Air = true
Pause-Elytra = true

[Surround]
Enabled = false
Drawn = true
Bind = 23
Surround = "STANDARD"
Completion = "AIR"
Center = "TELEPORT"
Switch = "NORMAL"
Blocks = 4.0
Strict = true
Reactive = true
Rotation = "PACKET"
Rotation-Center = false
Rotation-Random = false
Render = true
Render-Mode = "FILL"
Render-SafeColor = 671153920
Render-UnsafeColor = 687800320

[AntiAim]
Enabled = false
Drawn = true
Bind = 0
Yaw = "LINEAR"
Pitch = "NONE"
Rotate = "PACKET"

[ChatModifications]
Enabled = true
Drawn = false
Bind = 0
Time = "NA"
Prefix = true
Suffix = true
Colored = true

[FakePlayer]
Enabled = true
Drawn = false
Bind = 0
Inventory = true
Health = true

[Notifier]
Enabled = true
Drawn = false
Bind = 0
EnableNotify = false
PopNotify = false

[Portal]
Enabled = true
Drawn = false
Bind = 0
GodMode = false
Screens = true
Effect = false
Sounds = false

[Timer]
Enabled = false
Drawn = true
Bind = 0
Multiplier = 4.0

[XCarry]
Enabled = true
Drawn = false
Bind = 0

[ElytraFlight]
Enabled = false
Drawn = true
Bind = 0
Mode = "CONTROL"
Yaw = 30.0
Pitch = 30.0
Glide = 2.5
Ascend = 1.0
Descend = 1.0
Fall = 0.0
Firework = "NONE"
LockRotation = false
TakeOff = false
TakeOff-Timer = 0.2
Pause = true
Pause-Liquid = true
Pause-Collision = false

[NoSlow]
Enabled = true
Drawn = false
Bind = 0
Strict = true
AirStrict = true
SwitchStrict = true
PlaceStrict = false
GroundStrict = false
InventoryMove = true
InventoryMove-ArrowLook = 5.0
Items = true
SoulSand = false
Slime = false
Ice = true

[PacketFlight]
Enabled = false
Drawn = true
Bind = 0
Mode = "FAST"
Direction = "DOWN"
Factor = 1.0
Subdivisions = 4.0
AntiKick = true
LimitJitter = true
Overshoot = false
Stabilize = true

[ReverseStep]
Enabled = false
Drawn = true
Bind = 0
Mode = "MOTION"
Speed = 1.0
ShiftTicks = 1.0
Height = 2.0
OnlyHole = false
Webs = false

[Speed]
Enabled = false
Drawn = true
Bind = 47
Mode = "STRAFE_STRICT"
Timer = true
Timer-Ticks = 1.1
Accelerate = false
Boost = false
Liquid = false
Web = false

[Sprint]
Enabled = true
Drawn = false
Bind = 0
Mode = "DIRECTIONAL"
Safe = false
Strict = false

[Step]
Enabled = false
Drawn = true
Bind = 0
Mode = "NORMAL"
Height = 1.0

[Velocity]
Enabled = true
Drawn = false
Bind = 0
Horizontal = 0.0
Vertical = 0.0
NoPush = true
NoPush-Entities = true
NoPush-Blocks = true
NoPush-Liquid = true

[AntiHunger]
Enabled = false
Drawn = true
Bind = 0
StopSprint = true
StopJump = true

[AntiVoid]
Enabled = false
Drawn = true
Bind = 0
Mode = "SUSPEND"
Glide = 5.0
Float = 0.5

[Blink]
Enabled = false
Drawn = true
Bind = 0
Mode = "MANUAL"
SpawnFake = true
Delay = 5.0
Packets = 10
Distance = 10

[FastUse]
Enabled = true
Drawn = false
Bind = 0
Speed = 4.0
GhostFix = true
FastDrop = false
PacketUse = false
PacketUse-Gapple = false
PacketUse-Potions = true
EXP = true
Bow = false
Crystals = false
Blocks = false
SpawnEggs = false
Fireworks = false

[Interact]
Enabled = true
Drawn = false
Bind = 0
Reach = 0.0
Hand = "NONE"
GhostHand = false
NoSwing = false
IgnoreContainers = false
HitBox = true
HitBox-Extend = 0.0
HitBox-PlayersOnly = true
Liquid = false
HeightLimit = true
WorldBorder = false

[NoFall]
Enabled = false
Drawn = true
Bind = 0
Mode = "PACKET"
Distance = 2.0
Swap = "LEGIT"
Rubberband = 5.0
GlideSpeed = 1.5

[PingSpoof]
Enabled = false
Drawn = true
Bind = 0
Delay = 0.5

[SpeedMine]
Enabled = true
Drawn = true
Bind = 0
Mode = "PACKET"
Switch = "PACKET"
Damage = 1.0
Strict = false
Animation = false
Reset = false
Render = true
Render-Mode = "BOTH"

[CameraClip]
Enabled = false
Drawn = true
Bind = 0
Distance = 5.0

[Chams]
Enabled = false
Drawn = true
Bind = 0
Mode = "WIREMODEL"
Mode-Width = 1.08
Players = true
Players-Local = false
Mobs = true
Monsters = true
Crystals = true
Crystals-Scale = 1.0
Texture = false
Lighting = true
Blend = false
Transparent = true
Depth = true
Walls = true
XQZ = true
XQZ-XQZColor = 855258105
Highlight = true
Highlight-HighlightColor = 850355962

[ESP]
Enabled = false
Drawn = true
Bind = 0
Mode = "SHADER"
Width = 1.25
Players = true
Players-Color = -9018656
Passives = true
Passives-Color = -9018656
Neutrals = true
Neutrals-Color = -9018656
Hostiles = true
Hostiles-Color = -9018656
Items = true
Items-Color = -9018656
Crystals = true
Crystals-Color = -9018656
Vehicles = true
Vehicles-Color = -9018656

[FullBright]
Enabled = true
Drawn = false
Bind = 0

[HoleESP]
Enabled = true
Drawn = false
Bind = 0
Range = 5.0
Main = "FILL"
Main-Height = 0.1
Main-Width = 1.5
Outline = "OUTLINE"
Outline-Height = 0.1
Outline-Width = 1.5
Depth = true
Doubles = true
Void = false
Colors = true
Colors-Obsidian = 762733280
Colors-Mixed = 762733280
Colors-Bedrock = 762733280
Colors-Void = 771686400

[Nametags]
Enabled = false
Drawn = true
Bind = 0
Health = true
Ping = true
Gamemode = false
TotemPops = true
Background = true

[NoRender]
Enabled = true
Drawn = false
Bind = 0
Overlays = true
Overlays-Fire = true
Overlays-Liquid = true
Overlays-Block = true
Overlays-Boss = true
Fog = true
Fog-LiquidVision = true
Fog-Density = 0.0
Armor = true
Items = false
Fireworks = false
Particles = false
TileEntities = false
Maps = false
Skylight = false
HurtCamera = true
WitherSkull = true
Potion = false
FOV = true

**Comment by linustouchtips** [comment]
all cosmos modules configured for strict NCP

**Comment by Sxmurai** [comment]
i can confirm, block placements do work on cosmos, even with the default config on strict lol.

**Comment by Sxmurai** [comment]
and is that nametags im seeing in your config file???? lets fucking go
