### ISSUE TITLE
[BUG] Override setting in CA doesn't break crystals

### ISSUE THREAD

**Issue by fxbT-zzz** [momentumdevelopment/cosmos#126]
Issue:
* What is the bug that you would like addressed?
When the enemy's heath/armour is below the specified health/armour in the override setting, the CA places crystals but doesn't break them.

Context:
* When does this bug happen? Does it persist after restart/toggle?
It happens most of the time while faceplacing. It persists after restart and toggle.

Environment: 
* What other clients do you run, PC setup, relevant servers? How can this bug be replicated?
Happens with only cosmos in the mods folder. Happens on non-strict servers (tested on 5ms and 130ms). The bug can be replicated by spawning in a fake player and toggling crystal aura (turn up the override settings or make the fake player low health so it faceplaces).

Config:
* Attach any relevant parts of your config here.
Bug happens on default config as well as custom configs. I've tried messing around with the break, place and override settings but nothing seems to fix it.

**Comment by master7720** [comment]
close this issue?
