### ISSUE TITLE
[SUGGESTION] Config Manager / Preloaded Configs

### ISSUE THREAD

**Issue by unfidelity** [momentumdevelopment/cosmos#128]
- Make a new window for configs and default configs this would allow you to:
  - Load configs from a file
  - Load configs from a GitHub repository
  - Examples
  - ![gui](https://media.discordapp.net/attachments/869399835151835159/915834358890385499/unknown.png)
  - ![gui](https://cdn.discordapp.com/attachments/869399835151835159/915835578170376212/unknown.png)
- Create a config folder
  - Add a command to load configs from the config folder *config load <file>
  - Add a command to save configs to the config folder *config save <name> 
  - Add a command that can either update or overwrite an already existing config folder *config overwrite <name> or *config update <name> 
- Allow configs to be fully loaded without a restart

-Make a new repository for cosmos resources, 
  - where we could provide basic default configs for:
    - crystalpvp.cc
    - 2b2tpvp.net
    - strict.2b2tpvp.net
    - 2b2t.org
    - ohare.cc
    - endcrystal.me
    - 9b9t.com
    - etc.
 - Add another folder for media
   - readme resources like the banner and GUI images
   - montage resources
     - when I get around to it ill make an animated intro of the logo ykyk 
- Capes maybe? :^) boosters and og ofc

**Comment by master7720** [comment]
This would be very nice

**Comment by yagel15637** [comment]
@linustouchtips I can do the backend code for this if you haven't already

**Comment by unfidelity** [comment]
yes

**Comment by LuDaFan** [comment]
I agree to add the loading configuration. It will take me a long time to debug by hand.
