### ISSUE TITLE
[FEATURE SUGGESTION] Strict Strafe

### ISSUE THREAD

**Issue by TheCodDev** [momentumdevelopment/cosmos#13]
Hey guys, 

I really like your client. I think it is very good because it is free and is good for 2b2t, keep it up please!

But the main reason I am making this issue, is to try and request a feature. I would like you guys to add a Strict Strafe to the client, and just a Strafe in general. I see almost zero clients implement a proper strict strafe for 2b2t, and I do play on 2b2t, so I think it could really beneficial. As far as I know, the only clients with Strict Strafe's are salhack, which is outdated, and Future which is paid. So yeah, could you guys please add a strafe to the client, especially a Strict Strafe mode that would work well on 2b2t and other strict servers? I really appreciate it!

P.S. Does the client actually have a crypto miner?

Thanks! Let me know what you think!

**Comment by GentlemanMC** [comment]
this client is dead dont suggest shit anymore

**Comment by linustouchtips** [comment]
I will be adding a Step and Strafe soon.

**Comment by TheCodDev** [comment]
> 
> 
> I will be adding a Step and Strafe soon.

**Comment by TheCodDev** [comment]
> 
> 
> I will be adding a Step and Strafe soon.

**Comment by TheCodDev** [comment]
> 
> 
> I will be adding a Step and Strafe soon.

Will the strafe have an option for NCP/Strict/2b2t?

**Comment by linustouchtips** [comment]
Yes.

**Comment by AcaiBerii** [comment]
> this client is dead dont suggest shit anymore

me when the when the when

> I will be adding a Step and Strafe soon.

**Comment by Bjottt** [comment]
Yeah, its a crypto miner sadly

**Comment by master7720** [comment]
> this client is dead dont suggest shit anymore

*this client is dead* iq
