### ISSUE TITLE
[SUGGESTION] for thr aura

### ISSUE THREAD

**Issue by master7720** [momentumdevelopment/cosmos#130]
Issue:
make it so it attacks mobs

Context:
bc if your lazy like me and just want to afk then it will be useful

Environment: 
* What other clients do you run, PC setup, relevant servers?

Config:
* Attach any relevant parts of your config here.

**Comment by linustouchtips** [comment]
Already exists as a setting under the target parent setting.

**Comment by master7720** [comment]
> Already exists as a setting under the target parent setting.

ok nvm i am just dumb xd
