### ISSUE TITLE
Revert event handler back to FML

### ISSUE THREAD

**Issue by Sxmurai** [momentumdevelopment/cosmos#141]
So, I got bullied big time for the event system 

![image](https://user-images.githubusercontent.com/57580886/145516562-3ae2f86e-4a7d-40ec-83c7-9458178844a3.png)

Yes, I could've made it faster but apparently 10-20ms is slow, compared to 1-5ms (obviously)

Until I fix this, I say we revert back to the old event system

Should I care what people say? Probably not, it's a 5ms difference oh well, but if there's one with 1-5ms, it could 100% be faster.

**Comment by IUDevman** [comment]
Uh you know what milliseconds are bruv?

**Comment by Sxmurai** [comment]
Yes, I do. The 5ms example was just a number I threw out there. I also saw your post in the Discord. I was clearly joking when I said that he was bullying me, I was taking the criticism.

**Comment by Sxmurai** [comment]
There's really no need to put out there that I thought ~10ms was fast enough. I did get 0ms at times with the event handler, but it wasn't consistent enough to put as the delay, so I put the 10-20ms. It never actually got to 20ms, I was just estimating the time max.

Also, my computer is pretty shit. Not that it has to do with anything.

**Comment by IUDevman** [comment]
> If it makes you feel any better, I privated the event handler.

Bro lukflug

**Comment by yagel15637** [comment]
this issue makes me happy

**Comment by Sxmurai** [comment]
> > If it makes you feel any better, I privated the event handler.
> 
> Bro lukflug

What do you mean by this? I'm genuinely confused.

**Comment by FluorideHistorian** [comment]
i need to know

was that time for a single event
