### ISSUE TITLE
what is the point of this

### ISSUE THREAD

**Issue by bush-did-711** [momentumdevelopment/cosmos#147]
https://github.com/momentumdevelopment/cosmos/blob/a9533c5f80b1fac2c6d9573d1e7c99bdef4380f8/src/main/java/cope/cosmos/event/bus/EventBus.java#L86

why use a runnable and a consumer for this

**Comment by bush-did-711** [comment]
i am so confused there isnt even a thread or anything its literally just running the runnable you could delete the entire consumer thing and it would do the same thing

**Comment by linustouchtips** [comment]
@Sxmurai

**Comment by Sxmurai** [comment]
yeah, its shitty code and it wasnt 100% ready for cosmos. i thought it was but i was wrong. its getting a rewrite soon enough. i have a event bus in my 1.8.9 client im working on privately thats working decently well. ill either port it over to cosmos or ill use a different one on cosmos, or just use the FML event bus.

hopefully that helps, reopen if you have any other issues @bush-did-711

**Comment by bush-did-711** [comment]
u should use mine :P

**Comment by master7720** [comment]
^^^^
