### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by cattyngmd** [momentumdevelopment/cosmos#152]
Issue:
how to open clickgui

**Comment by cattyngmd** [comment]
HELP

**Comment by cattyngmd** [comment]
linhus @linustouchtips

**Comment by Sxmurai** [comment]
press right click russian man

**Comment by cattyngmd** [comment]
ok i will press right click!!! ty

**Comment by noatmc** [comment]
it didn't work for me :(, i also tried the left click

**Comment by cattyngmd** [comment]
> it didn't work for me :(, i also tried the left click

same ;((

**Comment by Sxmurai** [comment]
> press right shift russian man
!!!!!!!!!!!!

**Comment by Sxmurai** [comment]
my bad g, i meant to say right shift
