### ISSUE TITLE
Okay give imsge

### ISSUE THREAD

**Issue by Smasheroes** [momentumdevelopment/cosmos#154]
How to bind crystal aura

**Comment by master7720** [comment]
.....

**Comment by Sxmurai** [comment]
@Smasheroes Open the ClickGUI by pressing Right Shift, go to the Combat tab, right click AutoCrystal and you'll see a bind button that says `Bind: NONE`. Press that button and press whatever key you'd like to bind AutoCrystal too. Once it says for example `Bind: C`, you should have it binded.

Hope that helps, I'm closing this issue unless you have any further issues.
