### ISSUE TITLE
[SUGGESTION] xp for MiddleClick

### ISSUE THREAD

**Issue by master7720** [momentumdevelopment/cosmos#161]
Issue:
xp for MiddleClick

Context:
useful for if your crystaling someone and you need to repair your armor

Environment: 
* What other clients do you run, PC setup, relevant servers?

Config:
* Attach any relevant parts of your config here.

**Comment by Sxmurai** [comment]
So like silently swapping to an XP Bottle to mend via a middle click? Just making sure

**Comment by master7720** [comment]
yes
