### ISSUE TITLE
[BUG] ReverseStep max height doesn't work

### ISSUE THREAD

**Issue by fxbt-zzz** [momentumdevelopment/cosmos#162]
Issue:
* What is the bug that you would like addressed?
The max height setting on ReverseStep doesn't work and it still pulls you down no matter the height

Context:
* When does this bug happen? Does it persist after restart/toggle?
Always happens with ReverseStep

Environment: 
* What other clients do you run, PC setup, relevant servers? How can this bug be replicated?
Only cosmos in mods folder

Config:
* Attach any relevant parts of your config here.
Happens with default config and still happens when modifying the max height setting

**Comment by Sxmurai** [comment]
linus moment @linustouchtips

**Comment by master7720** [comment]
um it does work??

**Comment by Threasts** [comment]
> Issue:
> 
> * What is the bug that you would like addressed?
>   The max height setting on ReverseStep doesn't work and it still pulls you down no matter the height
> 
> Context:
> 
> * When does this bug happen? Does it persist after restart/toggle?
>   Always happens with ReverseStep
> 
> Environment:
> 
> * What other clients do you run, PC setup, relevant servers? How can this bug be replicated?
>   Only cosmos in mods folder
> 
> Config:
> 
> * Attach any relevant parts of your config here.
>   Happens with default config and still happens when modifying the max height setting

Well no fucking shit?

**Comment by Threasts** [comment]
step doesnt work at max height why should reverse step?
