### ISSUE TITLE
[BUG] AutoCrystal Raytrace

### ISSUE THREAD

**Issue by linustouchtips** [momentumdevelopment/cosmos#167]
Issue:
AutoCrystal incorrectly identifies certain positions as wall placements.

Context:
When AutoCrystal tries to place out in the open (i.e. not through walls)

Environment: 
N/A

Config:

[AutoCrystal]
Enabled = false
Drawn = true
Bind = 19
Explode = true
Explode-Range = 5.0
Explode-WallRange = 3.5
Explode-Delay = 86.0
Explode-RandomDelay = 0.0
Explode-SwitchDelay = 0.0
Explode-TicksExisted = 1.0
Explode-Damage = 5.0
Explode-LocalDamage = 5.0
Explode-Limit = 10.0
Explode-Packet = true
Explode-Inhibit = true
Explode-Hand = "SYNC"
Explode-Weakness = "NONE"
Place = true
Place-Range = 5.0
Place-WallRange = 3.5
Place-Delay = 0.0
Place-Damage = 5.0
Place-LocalDamage = 5.0
Place-Packet = true
Place-Interact = "STRICT"
Place-Raytrace = "DOUBLE"
Place-Hand = "SYNC"
Place-Switch = "NONE"
Pause = true
Pause-Health = 2.0
Pause-Safety = true
Pause-Eating = false
Pause-Mining = false
Pause-Mending = false
Override = true
Override-Health = 5.0
Override-Threshold = 0.0
Override-Armor = 0.0
Rotation = "PACKET"
Rotation-Limit = "NONE"
Rotation-When = "BOTH"
Rotation-Random = 0.0
Calculations = true
Calculations-Timing = "SEQUENTIAL"
Calculations-Placements = "NATIVE"
Calculations-Logic = "DAMAGE"
Calculations-Sync = "SOUND"
Calculations-Prediction = false
Calculations-IgnoreTerrain = false
Target = "CLOSEST"
Target-Range = 10.0
Target-Players = true
Target-Passives = false
Target-Neutrals = false
Target-Hostiles = false
Render = true
Render-Mode = "BOTH"
Render-Text = "TARGET"
Render-Width = 1.5

**Comment by master7720** [comment]
Bad config

**Comment by Sxmurai** [comment]
This isn't just a them issue, I've somewhat had this issue too

**Comment by linustouchtips** [comment]
Yeah, I somehow created this issue somewhere between the last release and this release since this wasn't an issue before
