### ISSUE TITLE
[BUG] GUI Minimizing

### ISSUE THREAD

**Issue by ImOnTopL** [momentumdevelopment/cosmos#174]
Issue:
* What is the bug that you would like addressed? when minimize and you open the clickgui the gui becomes white and when i maximize itits still white

Context:
* When does this bug happen? Does it persist after restart/toggle? yes when i do it again

Environment: 
* What other clients do you run, PC setup, relevant servers? How can this bug be replicated? optifine only

Config:
* Attach any relevant parts of your config here.default config cuz i didnt changed anything

**Comment by master7720** [comment]
"ImOnTopL" bad name

**Comment by ImOnTopL** [comment]
ok
