### ISSUE TITLE
[BUG] Dotted Shader

### ISSUE THREAD

**Issue by Sxmurai** [momentumdevelopment/cosmos#175]
Issue:
Dotted ESP doesn't show the dotted ESP

Context:
When entities/tile entities are in render distance to be able to render the dotted ESP

Environment: 
Only cosmos.

Using a RTX 3060 on maxed render settings

Config:
ESP Mode is on SHADER, and Shader mode is on DOTTED, looks like:

![2022-01-12_16 47 24](https://user-images.githubusercontent.com/57580886/149235282-0c437c54-7f0b-4a00-a415-ab9b21e4a03b.png)

**Comment by master7720** [comment]
"Using a RTX 3060" SHEEESH will buy it off you

**Comment by Sxmurai** [comment]
![image](https://user-images.githubusercontent.com/57580886/149236045-97e2b13d-fa2d-412f-ad27-b1d4e21fb911.png)

@linustouchtips Throws GL errors

**Comment by HausemasterIssue** [comment]
Damn u rich sxmurai

**Comment by Sxmurai** [comment]
This was fixed in god knows what commit, but it works well now
