### ISSUE TITLE
[SUGGESTION]

### ISSUE THREAD

**Issue by cone42** [momentumdevelopment/cosmos#179]
Issue:
* What is the feature you would like added?
*smart autotrap

Context:
* Why would this feature be useful? Have you tried any existing alternatives?
* this would be useful if the client could predict a good place to trap the target within a 5 block radius based upon the movements of the target

**Comment by arjunnain17** [comment]
throw more insight on "a good place to auto trap"

**Comment by linustouchtips** [comment]
^

**Comment by cone42** [comment]
i think i was high when i wrote this, I don't even know what I meant

**Comment by master7720** [comment]
> i think i was high when i wrote this, I don't even know what I meant

- 🤓

**Comment by cone42** [comment]
who
