### ISSUE TITLE
aura freezes my movement

### ISSUE THREAD

**Issue by swampww** [momentumdevelopment/cosmos#180]
Issue:
when im using aura, my movement and entites around me is frozen, and i cant turn off the module. also,i can look around and the chat and sounds working just fine, but i cant interact with something

Context:
its always happening when im turning on aura 

Environment: 
im using arch based linux os, and offical minecraft launcher

Config:
Enabled = true
Drawn = true
Bind = 34
Iterations = 5.0
Variation = 100.0
Range = 6.0
WallsRange = 6.0
Timing = "SEQUENTIAL"
Timing-Mode = "SWING"
Timing-Factor = 1.0
Timing-Delay = 1000.0
Timing-Ticks = 15.0
Timing-TPS = "AVERAGE"
Timing-Switch = 0.0
Timing-Random = 0.0
Timing-TicksExisted = 0.0
Timer = 0.0
FOV = 180.0
Weapon = "SWORD"
Weapon-OnlyWeapon = true
Weapon-32K = false
Weapon-Block = false
Rotation = "NONE"
Rotation-Limit = "NONE"
Bone = "BODY"
Rotation-Random = 0.0
Swing = "MAINHAND"
Raytrace = false
Packet = true
Teleport = false
Reactive = false
StopSprint = false
StopSneak = false
Pause = false
Pause-Health = 2.0
Pause-Eating = false
Pause-Mining = true
Pause-Mending = false
Switch = "NORMAL"
Target = "LOWESTHEALTH"
Target-Players = true
Target-Passives = false
Target-Neutrals = false
Target-Hostiles = false
Render = true

**Comment by notperry12345678902** [comment]
I use arch btw.

**Comment by master7720** [comment]
Bruh..

**Comment by abashir7866** [comment]
What distro specifically? That can help maybe. Are you using pure arch? Endeavor? Manjaro?

**Comment by master7720** [comment]
Manjaro on top!

**Comment by abashir7866** [comment]
I used to use arch... until my dumb ass deleted the partition with arch on it so I installed pop os cuz I cba reinstalling it lol
