### ISSUE TITLE
[SUGGESTION] Streamer Mode

### ISSUE THREAD

**Issue by Sxmurai** [momentumdevelopment/cosmos#181]
Issue:
Add streamer mode

Context:
girlboss milo asked

![image](https://user-images.githubusercontent.com/57580886/151259314-6bf940d4-9803-44ec-9919-ada22a6f85ec.png)

Environment: 
streaming lul

Config:
* Attach any relevant parts of your config here.

**Comment by master7720** [comment]
Or just use phobos with cosmos

**Comment by Sxmurai** [comment]
Finished in commit https://github.com/momentumdevelopment/cosmos/commit/2fa8ffbf9205343b4d65d1218da0a4644c2ee58e
