### ISSUE TITLE
[SUGGESTION] Resizable Gui

### ISSUE THREAD

**Issue by fakecash** [momentumdevelopment/cosmos#183]
Issue:
* What is the feature you would like added?
* Resizable ClickGui

Context:
* Why would this feature be useful? Have you tried any existing alternatives?
* Haven't seen any other client have it. It would work kind of like ImGui's or Skeet's with a notch in the bottom right corner.

**Comment by unfidelity** [comment]
Its already a feature there just isn't an indicator

**Comment by linustouchtips** [comment]
^
