### ISSUE TITLE
[SUGGESTION] Freecam

### ISSUE THREAD

**Issue by sqcred** [momentumdevelopment/cosmos#197]
I think a Freecam module would be pretty handy. For if youre stuck or want to see whats around you without moving

**Comment by Wolfsurge** [comment]
Already suggested.

**Comment by sqcred** [comment]
i see but i got removed again?

**Comment by Wolfsurge** [comment]
What?

**Comment by Wolfsurge** [comment]
Chances are that it didn't work properly

**Comment by sqcred** [comment]
ahhhh i see. well thanks for the reply
