### ISSUE TITLE
[SUGGESTION] Phase

### ISSUE THREAD

**Issue by Theboiboi8** [momentumdevelopment/cosmos#212]
Issue:
A module that, when enabled, allows the user to walk through blocks, horizontally and vertically.

Context:
This would be useful for entering bases or other underground/concealed/surrounded structures.

**Comment by Wolfsurge** [comment]
Correct me if I'm wrong, but isn't this just packet fly?

**Comment by Theboiboi8** [comment]
No, this allows the user to quite literally **phase** through blocks, completely ignoring hitboxes and collision.

**Comment by Sxmurai** [comment]
Unfortunately this isn't possible in the sense of just phasing freely as there's a thing called an anticheat. But good news, once I finish this PacketFly you'll be able to phase through blocks via PacketFly (as that's how everyone else does it)

**Comment by Sxmurai** [comment]
But if you're talking about freecam, we're re-adding that after we fix our combat modules c:

**Comment by Theboiboi8** [comment]
Closing as this issue is no longer needed

**Comment by swpq** [comment]
I disagree. This suggestion is still needed

**Comment by Theboiboi8** [comment]
But why, they literally said that Phase would be a feature in the upcoming Packet Fly whenever that gets finished, and as such there is no longer any need for a feature suggestion for an upcoming feature.

**Comment by swpq** [comment]
Please don't argue with swp (aliases: swp the king, swp the pvper, swp the catgirl, swp the queen, swp the king)

**Comment by Theboiboi8** [comment]
my brain melted reading those aliases

**Comment by swpq** [comment]
It's not nice to say things like this. Words can be hurtful.
