### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Random3131** [momentumdevelopment/cosmos#214]
Issue:
* What is the bug that you would like addressed?

Context:
* When does this bug happen? Does it persist after restart/toggle?
when using crystal aura it randomly crashes using latest dev build

Environment: 
* What other clients do you run, PC setup, relevant servers? How can this bug be replicated?

Config:
* Attach any relevant parts of your config here.
[21:33:38] [Client thread/INFO]: [net.minecraft.init.Bootstrap:func_179870_a:553]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  Cosmos (cosmos-1.4.0-dev.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 4/12/22 9:33 PM
Description: Unexpected error

java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at net.optifine.util.IteratorCache$IteratorReadOnly.next(IteratorCache.java:62)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:825)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1808)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1621)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1390)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at net.optifine.util.IteratorCache$IteratorReadOnly.next(IteratorCache.java:62)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:825)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1808)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1621)

-- Affected level --
Details:
	Level name: MpServer
	All players: 2 total; [EntityPlayerSP[''/1702, l='MpServer', x=-44.70, y=4.00, z=245.70], EntityPlayerPop['FakePlayer'/-1000, l='MpServer', x=-47.70, y=5.00, z=244.67]]
	Chunk stats: MultiplayerChunkCache: 81, 81
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (69,152,164), Chunk: (at 5,9,4 in 4,10; contains blocks 64,0,160 to 79,255,175), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 44068 game time, 22560 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 20 total; [EntityPlayerSP['mulberryaaa1'/1702, l='MpServer', x=-44.70, y=4.00, z=245.70], EntityOtherPlayerMP['enokitoraisu'/1701, l='MpServer', x=65.35, y=152.00, z=165.82], EntityOtherPlayerMP['Olype'/1699, l='MpServer', x=55.47, y=5.41, z=172.73], EntityPlayerPop['FakePlayer'/-1000, l='MpServer', x=-47.70, y=5.00, z=244.67], EntityEnderCrystal['entity.EnderCrystal.name'/166, l='MpServer', x=-45.50, y=37.00, z=251.50], EntityEnderCrystal['entity.EnderCrystal.name'/167, l='MpServer', x=-42.50, y=37.00, z=251.50], EntityPlayerPop['FakePlayer'/-1000, l='MpServer', x=-47.70, y=5.00, z=244.67], EntityEnderCrystal['entity.EnderCrystal.name'/168, l='MpServer', x=-40.50, y=37.00, z=251.50], EntityOtherPlayerMP['Olype'/1704, l='MpServer', x=65.84, y=152.00, z=165.13], EntityEnderCrystal['entity.EnderCrystal.name'/1705, l='MpServer', x=54.50, y=5.00, z=172.50], EntityEnderCrystal['entity.EnderCrystal.name'/169, l='MpServer', x=-33.50, y=38.00, z=251.50], EntityOtherPlayerMP['Olype'/1704, l='MpServer', x=56.97, y=98.25, z=174.40], EntityEnderCrystal['entity.EnderCrystal.name'/142, l='MpServer', x=-65.50, y=5.00, z=212.50], EntityOtherPlayerMP['Olype'/1704, l='MpServer', x=56.52, y=91.30, z=174.87], EntityEnderCrystal['entity.EnderCrystal.name'/179, l='MpServer', x=-21.50, y=31.00, z=284.50], EntityEnderCrystal['entity.EnderCrystal.name'/180, l='MpServer', x=-24.50, y=31.00, z=282.50], EntityEnderCrystal['entity.EnderCrystal.name'/150, l='MpServer', x=-59.50, y=31.00, z=201.50], EntityEnderCrystal['entity.EnderCrystal.name'/151, l='MpServer', x=-58.50, y=30.00, z=253.50], EntityEnderCrystal['entity.EnderCrystal.name'/152, l='MpServer', x=-58.50, y=17.00, z=243.50], EntityEnderCrystal['entity.EnderCrystal.name'/124, l='MpServer', x=-89.50, y=31.00, z=247.50]]
	Retry entities: 1 total; [EntityEnderCrystal['entity.EnderCrystal.name'/1705, l='MpServer', x=54.50, y=5.00, z=172.50]]
	Server brand: Paper (Velocity)
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4121555800 bytes (3930 MB) / 4664066048 bytes (4448 MB) up to 4966055936 bytes (4736 MB)
	JVM Flags: 8 total; -Xmn128M -Xmx4730M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 Optifine OptiFine_1.12.2_HD_U_G5 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID        | Version      | Source                        | Signature                                |
	|:------ |:--------- |:------------ |:----------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft | 1.12.2       | minecraft.jar                 | None                                     |
	| LCHIJA | mcp       | 9.42         | minecraft.jar                 | None                                     |
	| LCHIJA | FML       | 8.0.99.99    | forge-1.12.2-14.23.5.2860.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge     | 14.23.5.2860 | forge-1.12.2-14.23.5.2860.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | cosmos    | 1.4.0-dev    | cosmos-1.4.0-dev.jar          | None                                     |

	Loaded coremods (and transformers): 
Cosmos (cosmos-1.4.0-dev.jar)
  
	Launched Version: ForgeOptiFine 1.12.2
	LWJGL: 2.9.4
	OpenGL: AMD Radeon(TM) RX 5600M Series GL version 4.6.14761 Compatibility Profile Context 21.30.14 30.0.13014.8, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: С—esigma male pack
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x AMD Ryzen 5 4600H with Radeon Graphics 
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 5
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.14761 Compatibility Profile Context 21.30.14 30.0.13014.8
	OpenGlRenderer: AMD Radeon(TM) RX 5600M Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 12
[21:33:38] [Client thread/INFO]: [net.minecraft.init.Bootstrap:func_179870_a:553]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Admin\AppData\Roaming\.minecraft\crash-reports\crash-2022-04-12_21.33.44-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed
Here I am!
[VersionManager] Refreshing versions locally...
[VersionManager] Versions has been refreshed (95 ms)
[Launcher] Launcher exited.
[Launcher] Minecraft closed with exit code: -1
flush now
[Launcher] [Crash] Found crash report file: C:\Users\Admin\AppData\Roaming\.minecraft\crash-reports\crash-2022-04-12_21.23.49-client.txt
[Crash] Found crash report file: C:\Users\Admin\AppData\Roaming\.minecraft\crash-reports\crash-2022-04-12_21.23.49-client.txt
[Launcher] [Crash] Found crash report file: C:\Users\Admin\AppData\Roaming\.minecraft\crash-reports\crash-2022-04-12_21.25.29-client.txt
[Crash] Found crash report file: C:\Users\Admin\AppData\Roaming\.minecraft\crash-reports\crash-2022-04-12_21.25.29-client.txt
[Launcher] [Crash] Found crash report file: C:\Users\Admin\AppData\Roaming\.minecraft\crash-reports\crash-2022-04-12_21.30.15-server.txt
[Crash] Found crash report file: C:\Users\Admin\AppData\Roaming\.minecraft\crash-reports\crash-2022-04-12_21.30.15-server.txt
[Launcher] [Crash] Found crash report file: C:\Users\Admin\AppData\Roaming\.minecraft\crash-reports\crash-2022-04-12_21.33.44-client.txt
[Crash] Found crash report file: C:\Users\Admin\AppData\Roaming\.minecraft\crash-reports\crash-2022-04-12_21.33.44-client.txt
flush now
flush now

**Comment by linustouchtips** [comment]
Issue with AutoCrystal rewrite, should be resolved once the rewrite is finished

**Comment by Random3131** [comment]
okk

**Comment by linustouchtips** [comment]
fixed
