### ISSUE TITLE
[SUGGESTION] NoFall PACKET should not send extra packets

### ISSUE THREAD

**Issue by Doogie13** [momentumdevelopment/cosmos#215]
Issue:
* What is the feature you would like added?
NoFall Packet mode should edit existing packets rather than send new packets to spoof onground state

Context:
* Why would this feature be useful? Have you tried any existing alternatives?
Bypasses timer checks slightly better

Environment: 
* What other clients do you run, PC setup, relevant servers?
N/A

Config:
* Attach any relevant parts of your config here.
N/A

**Comment by Sxmurai** [comment]
I was talking to linus about this, I'm aware of this and I'll push this when I fix compatibility with Future's wallhack module
