### ISSUE TITLE
[QUESTION] Face place

### ISSUE THREAD

**Issue by GSstarGamer** [momentumdevelopment/cosmos#217]
Issue:
* What is the question you would like answered?
May I know how to face place in ca

**Comment by GSstarGamer** [comment]
> ኃጢአተኛ ነፍስህ ከመዳን በላይ ናት እናም ሰላምም ህመምም አታውቅም ማለቂያ የሌለው የባዶነት ቅዝቃዜ የንስሐ ጊዜ አብቅቷል, ምክንያቱም ወንጀሎችህ በክፉ አይነትህ ከማንኛውም ተልእኮ ይበልጣልና መጨረሻው ቅርብ ነው, የኃጢአት ![image](https://user-images.githubusercontent.com/44510312/167894542-b97d5083-121f-4c3f-a264-cc6b56b22c89.png) እቃዎች መዘንጋት ምስጋና ይጠብቃል. ወደ አላህ

what? i translate it but it has no thing related to minecraft

**Comment by linustouchtips** [comment]
LethalMultiplie=r
