### ISSUE TITLE
[BUG]potion hud element is fucked

### ISSUE THREAD

**Issue by GentlemanMC** [momentumdevelopment/cosmos#219]
Issue:
* What is the bug that you would like addressed?
lmao https://i.imgur.com/8Faf8Dt.png
Context:
* When does this bug happen? Does it persist after restart/toggle?
idk when i pop and gap at the same time i think
Environment: 
* What other clients do you run, PC setup, relevant servers? How can this bug be replicated?

Config:
* Attach any relevant parts of your config here.

**Comment by Sxmurai** [comment]
linus tech tips client:tm:

**Comment by GentlemanMC** [comment]
lol
