### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by zaucc** [momentumdevelopment/cosmos#222]
Issue:
I cant login with microsoft account

Context:
Every launch

Environment: 
i run earthhack and cosmos

Config:
default config ![7c5d1b8afe3c34c60e.png](https://user-images.githubusercontent.com/100954281/169695204-eb36c833-9d2e-4e65-ab27-e7226e0cea64.png)

**Comment by Sxmurai** [comment]
This is because the library we use is a bit wonky, and sometimes Microsoft becomes obese and thinks we're tryna steal ur account. Login to the minecraft website / launcher and do what it tells you to. It's only ever happened to me once with my own client, so idk microsoft is just obese

**Comment by zaucc** [comment]
ok thanks
