### ISSUE TITLE
[BUG] game crashes after restarting with esp on

### ISSUE THREAD

**Issue by PoomPoom123** [momentumdevelopment/cosmos#254]
Issue:
* What is the bug that you would like addressed?
game crashes after restarting with esp toggled on
Context:
* When does this bug happen? Does it persist after restart/toggle?
after restart of game with esp toggled on
Environment: 
* What other clients do you run, PC setup, relevant servers? How can this bug be replicated?
no other clients, bug can be replicated by toggling esp and closing game and trying to reopen
Config:
* Attach any relevant parts of your config here.
java.lang.nullpointerexception error rendering entity in world

**Comment by 1drw** [comment]
go to ur cosmos folder > presets > ur current config and manually disable esp then launch, it *should* work fine and u can reenable it from there. linus is aware of this issue

**Comment by PoomPoom123** [comment]
ye i already know how to fix it I just am telling the people why this happens cause some people dont know why this issue happens

**Comment by linustouchtips** [comment]
Fixed, will be included in next release
