### ISSUE TITLE
[SUGGESTION] make rotations compatible with phobos newbase

### ISSUE THREAD

**Issue by PoomPoom123** [momentumdevelopment/cosmos#255]
the rots get funky with phobos. any fixes?

**Comment by threevt** [comment]
fuck you no

**Comment by Zane2b2t** [comment]
> fuck you no

what is a 3vt doing here

thats the issue on phobos side not cosmos, i belive 3arthqu4ke is fixing it rn cus i made an issue

**Comment by 3arthqu4ke** [comment]
> thats the issue on phobos side not cosmos, i belive 3arthqu4ke is fixing it rn cus i made an issue

Uhm no?

**Comment by Wolfsurge** [comment]
kek

**Comment by 3arthqu4ke** [comment]
If they cancel on of their events [here](https://github.com/momentumdevelopment/cosmos/blob/main/src/main/java/cope/cosmos/asm/mixins/entity/player/MixinEntityPlayerSP.java) they should just be able to override rotations fine, I think? If cosmos rotations dont work with 3arthh4ck they most likely wont work with Future either Id say.

**Comment by unfidelity** [comment]
Use just cosmos or earthhack cosmos is designed to be a standalone client if you want a feature to be added make an issue here instead of using two clients

**Comment by Wolfsurge** [comment]
I'm just gonna close this because I doubt either side will fix this (I know I'm not going to :P) and like milo said, just use one, not both.
