### ISSUE TITLE
[SUGGESTION] Chat autocompletion pls

### ISSUE THREAD

**Issue by communist-cat** [momentumdevelopment/cosmos#257]
Issue:
Tab completion for client commands like any other client has out there

Context:
When you use the chat command stuff for the client a sane individual would want the autocomplete :)

**Comment by Wolfsurge** [comment]
> Any other client out there

Not really :P

**Comment by 1drw** [comment]
i suggest shut your mouth

**Comment by Wolfsurge** [comment]
@communist-cat , I suggest taking 1drw's advice very seriously.

**Comment by communist-cat** [comment]
@Wolfsurge i suggest you stfu lol

**Comment by Wolfsurge** [comment]
> @Wolfsurge i suggest you stfu lol
> Same for the other guy

I'm sorry but who tf are u

lol

**Comment by communist-cat** [comment]
@Wolfsurge yk what gfy lol great dev totally 💪

**Comment by Wolfsurge** [comment]
cope harder lel
