### ISSUE TITLE
[BUG] Can't join servers if blink is enabled

### ISSUE THREAD

**Issue by xiudeveloper** [momentumdevelopment/cosmos#258]
Issue:
Can not join servers if blink is left on

Context:
If I get disconnected from a server for using blink, I can't connect to any servers again.

Environment: 
I run 3arthh4ck, cosmos and trollhack, these other mods are likely not the cause as I have removed Cosmos from my mods folder and it has worked again. I disabled Blink manually in my configuration and it seemed to work fine.

Config:
https://gist.githubusercontent.com/xiudeveloper/47c931b9d42424e74d83cefaef620e44/raw/870d2bf4289859db8a57d34722cb113db16d121e/config.toml

**Comment by axberfanaccount** [comment]
known issue wont be fixed bcuz linus is poopy butthole

**Comment by linustouchtips** [comment]
Fixed already, will be included in next release

**Comment by 1drw** [comment]
oh my god oh my fucking god holy fucking shit
