### ISSUE TITLE
[SUGGESTION] add Setting

### ISSUE THREAD

**Issue by steve-ab6** [momentumdevelopment/cosmos#259]
Issue:
* What is the feature you would like added?
Add integer and string settings.

**Comment by Wolfsurge** [comment]
What modules would use them though?

Also, I believe you can effectively create an integer setting by using a float/double setting and setting the scale to 0, but this may be wrong.

**Comment by steve-ab6** [comment]
> What modules would use them though?
> The string setting can quickly customize the value, and it is difficult to accurately locate the value when the maximum value is large
> Also, I believe you can effectively create an integer setting by using a float/double setting and setting the scale to 0, but this may be wrong.
It works, thank you

**Comment by linustouchtips** [comment]
the new revamped command system coming in 1.5.0 will allow you to set values to exact numbers
