### ISSUE TITLE
[SUGGESTION] Nametags

### ISSUE THREAD

**Issue by Sxmurai** [momentumdevelopment/cosmos#30]
I never realized how much I kinda want/need nametags until I can't have them. Of course I could just pop in another client, but I really like Cosmos so far and it looks like a pretty solid client.

I'm also not asking you to copy future, but future's nametags look really nice, clean, and simple. Something like that people would be all over. Of course with a twist or something completely different that looks just as good or even better.

**Comment by linustouchtips** [comment]
Added to the roadmap for 1.0.2
