### ISSUE TITLE
[SUGGESTION] AutoArmor

### ISSUE THREAD

**Issue by Sxmurai** [momentumdevelopment/cosmos#52]
Can be named AutoArmour if ur not in the US, doesn't matter means the same thing.

Automatically equips the best armor piece

## Options

- Delay (int) 0-20 (4), The delay in ticks before equipping another piece of armor
- NoBinding (boolean) true, If to avoid equipping armor with the enchantment Curse of Binding
- InventoryOnly (boolean) false, If to only equip armor if the inventory GUI is open.

**Comment by linustouchtips** [comment]
- MotionStrict (boolean) false, stops motion before switching similar to offhand, works better on strict NCP servers

**Comment by Sxmurai** [comment]
Done in commit https://github.com/momentumdevelopment/cosmos/commit/e08ebc63b793d886c2c006b6d09496e5ddb404f7
