### ISSUE TITLE
[SUGGESTION] AntiWeb

### ISSUE THREAD

**Issue by Sxmurai** [momentumdevelopment/cosmos#58]
Stops you from getting stuck in webs (this module should make 0neb stop trying to web on 2b2tpvp)

## Options

- Mode (enum, [BOTTOM, FASTFALL, BOUNDINGBOX]) BOTTOM, How to prevent you from getting stuck in webs
  - BOTTOM: Instantly teleports you to the bottom of the web
  - FASTFALL: Makes you fall down the web faster
  - BOUNDINGBOX: Makes the web have a full bounding box

Also, somehow make a strict mode for 2b and whatever

**Comment by linustouchtips** [comment]
Exists in ReverseStep, should work in latest commit? Reopen with bug tag if this doesn't work/bypass since I didn't test it.
