### ISSUE TITLE
[SUGGESTION] LogoutSpots

### ISSUE THREAD

**Issue by Sxmurai** [momentumdevelopment/cosmos#60]
Shows where players became cringe and logged out during a fight

## Options
- Color (Color, [255, 0, 0]), The color to render the logout spot
- Mode (enum, [BOX, FILLED, FILLEDOUTLINE, CLAW]) FILLEDOUTLINE, How to render the logout spot bounding box
- Nametag (boolean) true, If to render a nametag above the logout spot
   - Name (boolean) true, If to show the username of the user that logged out
   - Coordinates (boolean) true, If to show the coordinates of the user that logged out

**Comment by Doogie13** [comment]
I have made a logoutspots and I will try to get it finished properly soon
