### ISSUE TITLE
[SUGGESTION] HUD Editor

### ISSUE THREAD

**Issue by Sxmurai** [momentumdevelopment/cosmos#85]
A full on customizable HUD Editor. This probably won't be done for awhile, but this is 100% something we should implement.

**Comment by linustouchtips** [comment]
if i do this, I want to make corner elements and stackable elements.

**Comment by GentlemanMC** [comment]
Do it pls

**Comment by linustouchtips** [comment]
i do like the current HUD though. It's clean.

**Comment by master7720** [comment]
yea

**Comment by Sxmurai** [comment]
well yeah, but its nice to have customization. if you dont want it ur the main dev, you can say no to it

**Comment by linustouchtips** [comment]
we shall see.

**Comment by linustouchtips** [comment]
don't think this will ever get added.

**Comment by master7720** [comment]
bruh why? a HUD Editor will be great for this client

**Comment by unfidelity** [comment]
Hud editor = user error
