### ISSUE TITLE
error when joining servers

### ISSUE THREAD

**Issue by master7720** [momentumdevelopment/cosmos#90]
any server i go to it says java.lang.NullPointerException

**Comment by linustouchtips** [comment]
send your logs

**Comment by CynicalMuffin** [comment]
@linustouchtips it happens for me too you get kicked when joining with the same error

**Comment by master7720** [comment]
> 
> 
> send your logs

bro that is the log java.lang.NullPointerException

**Comment by linustouchtips** [comment]
i need the actual file ...

**Comment by CynicalMuffin** [comment]
pc issue
