### ISSUE TITLE
[BUG] Client bugged in Dev Environment

### ISSUE THREAD

**Issue by ForBai** [momentumdevelopment/cosmos#92]
Issue:
Nothing works really
CommandManager doesn't work
pictures dont work
normal gui doesn't work

https://user-images.githubusercontent.com/79467608/141487672-510fe494-c1f3-4d0e-99c0-e84f4cc6a3c1.mp4

Context:

Environment: 
Just load it in intellij and do the other steps for it and then run the client

**Comment by Sxmurai** [comment]
how the fuck did you manage that

**Comment by Sxmurai** [comment]
it works fine on windows, i guess something isnt working right with linux. how fun

**Comment by linustouchtips** [comment]
chad linux user

**Comment by ForBai** [comment]
i just fu**ing hat linux some times!!!
Every time i load any client except PrestigeBase i get this error:
`Could not find net.minecraftforge:forgeBin:1.12.2-14.23.5.2847.
Searched in the following locations:
  - https://maven.minecraftforge.net/net/minecraftforge/forgeBin/1.12.2-14.23.5.2847/forgeBin-1.12.2-14.23.5.2847.pom
  - https://maven.minecraftforge.net/net/minecraftforge/forgeBin/1.12.2-14.23.5.2847/forgeBin-1.12.2-14.23.5.2847.jar
  - https://repo.maven.apache.org/maven2/net/minecraftforge/forgeBin/1.12.2-14.23.5.2847/forgeBin-1.12.2-14.23.5.2847.pom
  - https://repo.maven.apache.org/maven2/net/minecraftforge/forgeBin/1.12.2-14.23.5.2847/forgeBin-1.12.2-14.23.5.2847.jar
  - https://libraries.minecraft.net/net/minecraftforge/forgeBin/1.12.2-14.23.5.2847/forgeBin-1.12.2-14.23.5.2847.pom
  - https://libraries.minecraft.net/net/minecraftforge/forgeBin/1.12.2-14.23.5.2847/forgeBin-1.12.2-14.23.5.2847.jar
  - https://repo.spongepowered.org/repository/maven-public/net/minecraftforge/forgeBin/1.12.2-14.23.5.2847/forgeBin-1.12.2-14.23.5.2847.pom
  - https://repo.spongepowered.org/repository/maven-public/net/minecraftforge/forgeBin/1.12.2-14.23.5.2847/forgeBin-1.12.2-14.23.5.2847.jar
  - file:/home/lars/.gradle/caches/minecraft/deobfedDeps/net/minecraftforge/forgeBin/1.12.2-14.23.5.2847/forgeBin-1.12.2-14.23.5.2847.pom
  - file:/home/lars/.gradle/caches/minecraft/deobfedDeps/net/minecraftforge/forgeBin/1.12.2-14.23.5.2847/forgeBin-1.12.2-14.23.5.2847.jar
  - file:/home/lars/.gradle/caches/minecraft/net/minecraftforge/forge/1.12.2-14.23.5.2847/stable/39/forgeBin-1.12.2-14.23.5.2847.jar
  - file:/home/lars/.gradle/caches/minecraft/net/minecraftforge/forge/1.12.2-14.23.5.2847/stable/39/forgeBin.jar
Required by:
    project :

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

`
and then when i ask the creator he says there is no error 
btw i hate linux

**Comment by Sxmurai** [comment]
run `./gradlrew setupDecompWorkspace`. run cleanCache if you need to and don't mind re-caching any other projects you may have.

**Comment by linustouchtips** [comment]
^^^ run setupDecompWorkspace

**Comment by GentlemanMC** [comment]
> i just fu**ing hat linux some times!!! Every time i load any client except PrestigeBase i get this error:
> 
> Could not find net.minecraftforge:forgeBin:1.12.2-14.23.5.2847. Searched in the following locations:
> 
> * https://maven.minecraftforge.net/net/minecraftforge/forgeBin/1.12.2-14.23.5.2847/forgeBin-1.12.2-14.23.5.2847.pom
> * https://maven.minecraftforge.net/net/minecraftforge/forgeBin/1.12.2-14.23.5.2847/forgeBin-1.12.2-14.23.5.2847.jar
> * https://repo.maven.apache.org/maven2/net/minecraftforge/forgeBin/1.12.2-14.23.5.2847/forgeBin-1.12.2-14.23.5.2847.pom
> * https://repo.maven.apache.org/maven2/net/minecraftforge/forgeBin/1.12.2-14.23.5.2847/forgeBin-1.12.2-14.23.5.2847.jar
> * https://libraries.minecraft.net/net/minecraftforge/forgeBin/1.12.2-14.23.5.2847/forgeBin-1.12.2-14.23.5.2847.pom
> * https://libraries.minecraft.net/net/minecraftforge/forgeBin/1.12.2-14.23.5.2847/forgeBin-1.12.2-14.23.5.2847.jar
> * https://repo.spongepowered.org/repository/maven-public/net/minecraftforge/forgeBin/1.12.2-14.23.5.2847/forgeBin-1.12.2-14.23.5.2847.pom
> * https://repo.spongepowered.org/repository/maven-public/net/minecraftforge/forgeBin/1.12.2-14.23.5.2847/forgeBin-1.12.2-14.23.5.2847.jar
> * file:/home/lars/.gradle/caches/minecraft/deobfedDeps/net/minecraftforge/forgeBin/1.12.2-14.23.5.2847/forgeBin-1.12.2-14.23.5.2847.pom
> * file:/home/lars/.gradle/caches/minecraft/deobfedDeps/net/minecraftforge/forgeBin/1.12.2-14.23.5.2847/forgeBin-1.12.2-14.23.5.2847.jar
> * file:/home/lars/.gradle/caches/minecraft/net/minecraftforge/forge/1.12.2-14.23.5.2847/stable/39/forgeBin-1.12.2-14.23.5.2847.jar
> * file:/home/lars/.gradle/caches/minecraft/net/minecraftforge/forge/1.12.2-14.23.5.2847/stable/39/forgeBin.jar
>   Required by:
>   project :
> 
> Possible solution:
> 
> * Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
> 
> and then when i ask the creator he says there is no error btw i hate linux

i have 1 question...

why the fuck are u using prestigebase

**Comment by Gopro336** [comment]
for real tho

**Comment by ForBai** [comment]
Just testing with client bases

**Comment by Doogie13** [comment]
images not loading properly happens with me on windows 10 so its not that
It works in non dev env so idrc and it doesnt make anything unusable
