### ISSUE TITLE
[BUG] Threadmanager, Eventmanager, OpenGL Errors

### ISSUE THREAD

**Issue by CynicalMuffin** [momentumdevelopment/cosmos#96]
Holefill and maybe surround and autocrystal is causing a lot of issues once again 
reduction of half the usual fps along with spamming logs
Items still have the enchantment glint at random times usually when my ca and chams(Wiremodel) are on
Lag spikes still occur

Here is my 29k lines error log ig

[logs.txt](https://github.com/momentumdevelopment/cosmos/files/7533445/logs.txt)

**Comment by Sxmurai** [comment]
how fun fun fun fun

**Comment by Sxmurai** [comment]
I **SHOULD** have fixed holemanager finally at https://github.com/momentumdevelopment/cosmos/commit/bc6c914d165579ec775bbee89711a42a28b89867

**Comment by CynicalMuffin** [comment]
@Sxmurai Yup its all fixed now holemanager no longer has any issues
