### ISSUE TITLE
[BUG] Exceptions with clickgui and autocrystal

### ISSUE THREAD

**Issue by ghost** [momentumdevelopment/cosmos#97]
Not sure if this is an issue does not cause any lag what so ever but it does spam logs so 

When eating gapples and using autocrystal:
[iseating.txt](https://github.com/momentumdevelopment/cosmos/files/7538486/iseating.txt) [This is spammed about once every 1/4th of a second]

When clickgui is open and you switch module categories:
[clickgui.txt](https://github.com/momentumdevelopment/cosmos/files/7538502/clickgui.txt) [This is for opening GUI and switching from combat to movement category and closing GUI]

**Comment by Sxmurai** [comment]
that should have been fixed, waiting on linus to push the hotfix with the HoleManager fix. @linustouchtips you planning on doing that?

**Comment by Sxmurai** [comment]
the clickgui errors have been a thing for awhile, ill probably get to fixing that after school

**Comment by Wolfsurge** [comment]
This can be closed can't it? (New CA & GUI)

**Comment by Wolfsurge** [comment]
@linustouchtips close this
